  server:
    port: 8887
  druid:
    url: jdbc:mysql://localhost:3306/zhbh?useUnicode=true&characterEncoding=utf-8&&useSSL=false
    username: root
    password: Pass99123
    initialSize: 1
    minIdle: 1
    maxActive: 20
    validationQuery: SELECT 1 FROM DUAL
    filter: stat


  mybatis:
    type-aliases-package: com.jtzh.entity
    mapper-locations: classpath:mapper/*.xml
    config-locations: classpath:mybatis-config.xml
    configuration:
        mapUnderscoreToCamelCase: true

  mapper:
      mappers:
          - com.jtzh.common.base.BaseMapper
      not-empty: false
      identity: MYSQL

  javamelody:
    advisor-auto-proxy-creator-enabled: false
