package com.jtzh.mapper;

import com.jtzh.entity.Cgchuli;
import com.jtzh.entity.CgchuliExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CgchuliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int countByExample(CgchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int deleteByExample(CgchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int insert(Cgchuli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int insertSelective(Cgchuli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    List<Cgchuli> selectByExample(CgchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    Cgchuli selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cgchuli record, @Param("example") CgchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int updateByExample(@Param("record") Cgchuli record, @Param("example") CgchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int updateByPrimaryKeySelective(Cgchuli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int updateByPrimaryKey(Cgchuli record);
    int yichuli(Cgchuli cgchuli);
    int shenghe(Cgchuli cgchuli);
    /*List <Cgchuli> findbyshangbaoid(int id);*/
    List <Cgchuli> cgchulifindbyId(String shangbaoid);
}