package com.jtzh.mapper;

import com.jtzh.entity.Hwchuli;
import com.jtzh.entity.HwchuliExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HwchuliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int countByExample(HwchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int deleteByExample(HwchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int insert(Hwchuli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int insertSelective(Hwchuli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    List<Hwchuli> selectByExample(HwchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    Hwchuli selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") Hwchuli record, @Param("example") HwchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int updateByExample(@Param("record") Hwchuli record, @Param("example") HwchuliExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int updateByPrimaryKeySelective(Hwchuli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    int updateByPrimaryKey(Hwchuli record);
    int yichuli(Hwchuli hwchuli);
    int shenghe(Hwchuli hwchuli);
    /*List <Hwchuli> findbyshangbaoid(int id);*/
    List <Hwchuli> hwchulifindbyId(String shangbaoid);
}