package com.jtzh.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CgchuliExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public CgchuliExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andShangbaoidIsNull() {
            addCriterion("shangbaoid is null");
            return (Criteria) this;
        }

        public Criteria andShangbaoidIsNotNull() {
            addCriterion("shangbaoid is not null");
            return (Criteria) this;
        }

        public Criteria andShangbaoidEqualTo(Integer value) {
            addCriterion("shangbaoid =", value, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andShangbaoidNotEqualTo(Integer value) {
            addCriterion("shangbaoid <>", value, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andShangbaoidGreaterThan(Integer value) {
            addCriterion("shangbaoid >", value, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andShangbaoidGreaterThanOrEqualTo(Integer value) {
            addCriterion("shangbaoid >=", value, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andShangbaoidLessThan(Integer value) {
            addCriterion("shangbaoid <", value, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andShangbaoidLessThanOrEqualTo(Integer value) {
            addCriterion("shangbaoid <=", value, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andShangbaoidIn(List<Integer> values) {
            addCriterion("shangbaoid in", values, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andShangbaoidNotIn(List<Integer> values) {
            addCriterion("shangbaoid not in", values, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andShangbaoidBetween(Integer value1, Integer value2) {
            addCriterion("shangbaoid between", value1, value2, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andShangbaoidNotBetween(Integer value1, Integer value2) {
            addCriterion("shangbaoid not between", value1, value2, "shangbaoid");
            return (Criteria) this;
        }

        public Criteria andChulirenIsNull() {
            addCriterion("chuliren is null");
            return (Criteria) this;
        }

        public Criteria andChulirenIsNotNull() {
            addCriterion("chuliren is not null");
            return (Criteria) this;
        }

        public Criteria andChulirenEqualTo(String value) {
            addCriterion("chuliren =", value, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenNotEqualTo(String value) {
            addCriterion("chuliren <>", value, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenGreaterThan(String value) {
            addCriterion("chuliren >", value, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenGreaterThanOrEqualTo(String value) {
            addCriterion("chuliren >=", value, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenLessThan(String value) {
            addCriterion("chuliren <", value, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenLessThanOrEqualTo(String value) {
            addCriterion("chuliren <=", value, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenLike(String value) {
            addCriterion("chuliren like", value, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenNotLike(String value) {
            addCriterion("chuliren not like", value, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenIn(List<String> values) {
            addCriterion("chuliren in", values, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenNotIn(List<String> values) {
            addCriterion("chuliren not in", values, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenBetween(String value1, String value2) {
            addCriterion("chuliren between", value1, value2, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulirenNotBetween(String value1, String value2) {
            addCriterion("chuliren not between", value1, value2, "chuliren");
            return (Criteria) this;
        }

        public Criteria andChulitimeIsNull() {
            addCriterion("chulitime is null");
            return (Criteria) this;
        }

        public Criteria andChulitimeIsNotNull() {
            addCriterion("chulitime is not null");
            return (Criteria) this;
        }

        public Criteria andChulitimeEqualTo(Date value) {
            addCriterion("chulitime =", value, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulitimeNotEqualTo(Date value) {
            addCriterion("chulitime <>", value, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulitimeGreaterThan(Date value) {
            addCriterion("chulitime >", value, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulitimeGreaterThanOrEqualTo(Date value) {
            addCriterion("chulitime >=", value, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulitimeLessThan(Date value) {
            addCriterion("chulitime <", value, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulitimeLessThanOrEqualTo(Date value) {
            addCriterion("chulitime <=", value, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulitimeIn(List<Date> values) {
            addCriterion("chulitime in", values, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulitimeNotIn(List<Date> values) {
            addCriterion("chulitime not in", values, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulitimeBetween(Date value1, Date value2) {
            addCriterion("chulitime between", value1, value2, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulitimeNotBetween(Date value1, Date value2) {
            addCriterion("chulitime not between", value1, value2, "chulitime");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuIsNull() {
            addCriterion("chulimiaoshu is null");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuIsNotNull() {
            addCriterion("chulimiaoshu is not null");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuEqualTo(String value) {
            addCriterion("chulimiaoshu =", value, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuNotEqualTo(String value) {
            addCriterion("chulimiaoshu <>", value, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuGreaterThan(String value) {
            addCriterion("chulimiaoshu >", value, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuGreaterThanOrEqualTo(String value) {
            addCriterion("chulimiaoshu >=", value, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuLessThan(String value) {
            addCriterion("chulimiaoshu <", value, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuLessThanOrEqualTo(String value) {
            addCriterion("chulimiaoshu <=", value, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuLike(String value) {
            addCriterion("chulimiaoshu like", value, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuNotLike(String value) {
            addCriterion("chulimiaoshu not like", value, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuIn(List<String> values) {
            addCriterion("chulimiaoshu in", values, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuNotIn(List<String> values) {
            addCriterion("chulimiaoshu not in", values, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuBetween(String value1, String value2) {
            addCriterion("chulimiaoshu between", value1, value2, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andChulimiaoshuNotBetween(String value1, String value2) {
            addCriterion("chulimiaoshu not between", value1, value2, "chulimiaoshu");
            return (Criteria) this;
        }

        public Criteria andSheherenIsNull() {
            addCriterion("sheheren is null");
            return (Criteria) this;
        }

        public Criteria andSheherenIsNotNull() {
            addCriterion("sheheren is not null");
            return (Criteria) this;
        }

        public Criteria andSheherenEqualTo(String value) {
            addCriterion("sheheren =", value, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenNotEqualTo(String value) {
            addCriterion("sheheren <>", value, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenGreaterThan(String value) {
            addCriterion("sheheren >", value, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenGreaterThanOrEqualTo(String value) {
            addCriterion("sheheren >=", value, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenLessThan(String value) {
            addCriterion("sheheren <", value, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenLessThanOrEqualTo(String value) {
            addCriterion("sheheren <=", value, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenLike(String value) {
            addCriterion("sheheren like", value, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenNotLike(String value) {
            addCriterion("sheheren not like", value, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenIn(List<String> values) {
            addCriterion("sheheren in", values, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenNotIn(List<String> values) {
            addCriterion("sheheren not in", values, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenBetween(String value1, String value2) {
            addCriterion("sheheren between", value1, value2, "sheheren");
            return (Criteria) this;
        }

        public Criteria andSheherenNotBetween(String value1, String value2) {
            addCriterion("sheheren not between", value1, value2, "sheheren");
            return (Criteria) this;
        }

        public Criteria andShehetimeIsNull() {
            addCriterion("shehetime is null");
            return (Criteria) this;
        }

        public Criteria andShehetimeIsNotNull() {
            addCriterion("shehetime is not null");
            return (Criteria) this;
        }

        public Criteria andShehetimeEqualTo(Date value) {
            addCriterion("shehetime =", value, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehetimeNotEqualTo(Date value) {
            addCriterion("shehetime <>", value, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehetimeGreaterThan(Date value) {
            addCriterion("shehetime >", value, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("shehetime >=", value, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehetimeLessThan(Date value) {
            addCriterion("shehetime <", value, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehetimeLessThanOrEqualTo(Date value) {
            addCriterion("shehetime <=", value, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehetimeIn(List<Date> values) {
            addCriterion("shehetime in", values, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehetimeNotIn(List<Date> values) {
            addCriterion("shehetime not in", values, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehetimeBetween(Date value1, Date value2) {
            addCriterion("shehetime between", value1, value2, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehetimeNotBetween(Date value1, Date value2) {
            addCriterion("shehetime not between", value1, value2, "shehetime");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuIsNull() {
            addCriterion("shehemiaoshu is null");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuIsNotNull() {
            addCriterion("shehemiaoshu is not null");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuEqualTo(String value) {
            addCriterion("shehemiaoshu =", value, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuNotEqualTo(String value) {
            addCriterion("shehemiaoshu <>", value, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuGreaterThan(String value) {
            addCriterion("shehemiaoshu >", value, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuGreaterThanOrEqualTo(String value) {
            addCriterion("shehemiaoshu >=", value, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuLessThan(String value) {
            addCriterion("shehemiaoshu <", value, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuLessThanOrEqualTo(String value) {
            addCriterion("shehemiaoshu <=", value, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuLike(String value) {
            addCriterion("shehemiaoshu like", value, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuNotLike(String value) {
            addCriterion("shehemiaoshu not like", value, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuIn(List<String> values) {
            addCriterion("shehemiaoshu in", values, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuNotIn(List<String> values) {
            addCriterion("shehemiaoshu not in", values, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuBetween(String value1, String value2) {
            addCriterion("shehemiaoshu between", value1, value2, "shehemiaoshu");
            return (Criteria) this;
        }

        public Criteria andShehemiaoshuNotBetween(String value1, String value2) {
            addCriterion("shehemiaoshu not between", value1, value2, "shehemiaoshu");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cgchuli
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 24 10:13:50 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cgchuli
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}