package com.jtzh.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CgshangbaoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public CgshangbaoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCategoriesIsNull() {
            addCriterion("Categories is null");
            return (Criteria) this;
        }

        public Criteria andCategoriesIsNotNull() {
            addCriterion("Categories is not null");
            return (Criteria) this;
        }

        public Criteria andCategoriesEqualTo(String value) {
            addCriterion("Categories =", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesNotEqualTo(String value) {
            addCriterion("Categories <>", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesGreaterThan(String value) {
            addCriterion("Categories >", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesGreaterThanOrEqualTo(String value) {
            addCriterion("Categories >=", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesLessThan(String value) {
            addCriterion("Categories <", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesLessThanOrEqualTo(String value) {
            addCriterion("Categories <=", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesLike(String value) {
            addCriterion("Categories like", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesNotLike(String value) {
            addCriterion("Categories not like", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesIn(List<String> values) {
            addCriterion("Categories in", values, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesNotIn(List<String> values) {
            addCriterion("Categories not in", values, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesBetween(String value1, String value2) {
            addCriterion("Categories between", value1, value2, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesNotBetween(String value1, String value2) {
            addCriterion("Categories not between", value1, value2, "categories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesIsNull() {
            addCriterion("smallcategories is null");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesIsNotNull() {
            addCriterion("smallcategories is not null");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesEqualTo(String value) {
            addCriterion("smallcategories =", value, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesNotEqualTo(String value) {
            addCriterion("smallcategories <>", value, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesGreaterThan(String value) {
            addCriterion("smallcategories >", value, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesGreaterThanOrEqualTo(String value) {
            addCriterion("smallcategories >=", value, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesLessThan(String value) {
            addCriterion("smallcategories <", value, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesLessThanOrEqualTo(String value) {
            addCriterion("smallcategories <=", value, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesLike(String value) {
            addCriterion("smallcategories like", value, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesNotLike(String value) {
            addCriterion("smallcategories not like", value, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesIn(List<String> values) {
            addCriterion("smallcategories in", values, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesNotIn(List<String> values) {
            addCriterion("smallcategories not in", values, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesBetween(String value1, String value2) {
            addCriterion("smallcategories between", value1, value2, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSmallcategoriesNotBetween(String value1, String value2) {
            addCriterion("smallcategories not between", value1, value2, "smallcategories");
            return (Criteria) this;
        }

        public Criteria andSubmittimeIsNull() {
            addCriterion("submittime is null");
            return (Criteria) this;
        }

        public Criteria andSubmittimeIsNotNull() {
            addCriterion("submittime is not null");
            return (Criteria) this;
        }

        public Criteria andSubmittimeEqualTo(Date value) {
            addCriterion("submittime =", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeNotEqualTo(Date value) {
            addCriterion("submittime <>", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeGreaterThan(Date value) {
            addCriterion("submittime >", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeGreaterThanOrEqualTo(Date value) {
            addCriterion("submittime >=", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeLessThan(Date value) {
            addCriterion("submittime <", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeLessThanOrEqualTo(Date value) {
            addCriterion("submittime <=", value, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeIn(List<Date> values) {
            addCriterion("submittime in", values, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeNotIn(List<Date> values) {
            addCriterion("submittime not in", values, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeBetween(Date value1, Date value2) {
            addCriterion("submittime between", value1, value2, "submittime");
            return (Criteria) this;
        }

        public Criteria andSubmittimeNotBetween(Date value1, Date value2) {
            addCriterion("submittime not between", value1, value2, "submittime");
            return (Criteria) this;
        }

        public Criteria andDizhi1IsNull() {
            addCriterion("dizhi1 is null");
            return (Criteria) this;
        }

        public Criteria andDizhi1IsNotNull() {
            addCriterion("dizhi1 is not null");
            return (Criteria) this;
        }

        public Criteria andDizhi1EqualTo(String value) {
            addCriterion("dizhi1 =", value, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1NotEqualTo(String value) {
            addCriterion("dizhi1 <>", value, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1GreaterThan(String value) {
            addCriterion("dizhi1 >", value, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1GreaterThanOrEqualTo(String value) {
            addCriterion("dizhi1 >=", value, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1LessThan(String value) {
            addCriterion("dizhi1 <", value, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1LessThanOrEqualTo(String value) {
            addCriterion("dizhi1 <=", value, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1Like(String value) {
            addCriterion("dizhi1 like", value, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1NotLike(String value) {
            addCriterion("dizhi1 not like", value, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1In(List<String> values) {
            addCriterion("dizhi1 in", values, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1NotIn(List<String> values) {
            addCriterion("dizhi1 not in", values, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1Between(String value1, String value2) {
            addCriterion("dizhi1 between", value1, value2, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi1NotBetween(String value1, String value2) {
            addCriterion("dizhi1 not between", value1, value2, "dizhi1");
            return (Criteria) this;
        }

        public Criteria andDizhi2IsNull() {
            addCriterion("dizhi2 is null");
            return (Criteria) this;
        }

        public Criteria andDizhi2IsNotNull() {
            addCriterion("dizhi2 is not null");
            return (Criteria) this;
        }

        public Criteria andDizhi2EqualTo(String value) {
            addCriterion("dizhi2 =", value, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2NotEqualTo(String value) {
            addCriterion("dizhi2 <>", value, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2GreaterThan(String value) {
            addCriterion("dizhi2 >", value, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2GreaterThanOrEqualTo(String value) {
            addCriterion("dizhi2 >=", value, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2LessThan(String value) {
            addCriterion("dizhi2 <", value, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2LessThanOrEqualTo(String value) {
            addCriterion("dizhi2 <=", value, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2Like(String value) {
            addCriterion("dizhi2 like", value, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2NotLike(String value) {
            addCriterion("dizhi2 not like", value, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2In(List<String> values) {
            addCriterion("dizhi2 in", values, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2NotIn(List<String> values) {
            addCriterion("dizhi2 not in", values, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2Between(String value1, String value2) {
            addCriterion("dizhi2 between", value1, value2, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andDizhi2NotBetween(String value1, String value2) {
            addCriterion("dizhi2 not between", value1, value2, "dizhi2");
            return (Criteria) this;
        }

        public Criteria andPeopleIsNull() {
            addCriterion("people is null");
            return (Criteria) this;
        }

        public Criteria andPeopleIsNotNull() {
            addCriterion("people is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleEqualTo(String value) {
            addCriterion("people =", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotEqualTo(String value) {
            addCriterion("people <>", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleGreaterThan(String value) {
            addCriterion("people >", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleGreaterThanOrEqualTo(String value) {
            addCriterion("people >=", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleLessThan(String value) {
            addCriterion("people <", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleLessThanOrEqualTo(String value) {
            addCriterion("people <=", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleLike(String value) {
            addCriterion("people like", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotLike(String value) {
            addCriterion("people not like", value, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleIn(List<String> values) {
            addCriterion("people in", values, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotIn(List<String> values) {
            addCriterion("people not in", values, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleBetween(String value1, String value2) {
            addCriterion("people between", value1, value2, "people");
            return (Criteria) this;
        }

        public Criteria andPeopleNotBetween(String value1, String value2) {
            addCriterion("people not between", value1, value2, "people");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNull() {
            addCriterion("photo is null");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNotNull() {
            addCriterion("photo is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoEqualTo(String value) {
            addCriterion("photo =", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotEqualTo(String value) {
            addCriterion("photo <>", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThan(String value) {
            addCriterion("photo >", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("photo >=", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLessThan(String value) {
            addCriterion("photo <", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLessThanOrEqualTo(String value) {
            addCriterion("photo <=", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLike(String value) {
            addCriterion("photo like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotLike(String value) {
            addCriterion("photo not like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoIn(List<String> values) {
            addCriterion("photo in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotIn(List<String> values) {
            addCriterion("photo not in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoBetween(String value1, String value2) {
            addCriterion("photo between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotBetween(String value1, String value2) {
            addCriterion("photo not between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andMiaoshuIsNull() {
            addCriterion("miaoshu is null");
            return (Criteria) this;
        }

        public Criteria andMiaoshuIsNotNull() {
            addCriterion("miaoshu is not null");
            return (Criteria) this;
        }

        public Criteria andMiaoshuEqualTo(String value) {
            addCriterion("miaoshu =", value, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuNotEqualTo(String value) {
            addCriterion("miaoshu <>", value, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuGreaterThan(String value) {
            addCriterion("miaoshu >", value, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuGreaterThanOrEqualTo(String value) {
            addCriterion("miaoshu >=", value, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuLessThan(String value) {
            addCriterion("miaoshu <", value, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuLessThanOrEqualTo(String value) {
            addCriterion("miaoshu <=", value, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuLike(String value) {
            addCriterion("miaoshu like", value, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuNotLike(String value) {
            addCriterion("miaoshu not like", value, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuIn(List<String> values) {
            addCriterion("miaoshu in", values, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuNotIn(List<String> values) {
            addCriterion("miaoshu not in", values, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuBetween(String value1, String value2) {
            addCriterion("miaoshu between", value1, value2, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andMiaoshuNotBetween(String value1, String value2) {
            addCriterion("miaoshu not between", value1, value2, "miaoshu");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNull() {
            addCriterion("isdeleted is null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIsNotNull() {
            addCriterion("isdeleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeletedEqualTo(String value) {
            addCriterion("isdeleted =", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotEqualTo(String value) {
            addCriterion("isdeleted <>", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThan(String value) {
            addCriterion("isdeleted >", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedGreaterThanOrEqualTo(String value) {
            addCriterion("isdeleted >=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThan(String value) {
            addCriterion("isdeleted <", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLessThanOrEqualTo(String value) {
            addCriterion("isdeleted <=", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedLike(String value) {
            addCriterion("isdeleted like", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotLike(String value) {
            addCriterion("isdeleted not like", value, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedIn(List<String> values) {
            addCriterion("isdeleted in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotIn(List<String> values) {
            addCriterion("isdeleted not in", values, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedBetween(String value1, String value2) {
            addCriterion("isdeleted between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andIsdeletedNotBetween(String value1, String value2) {
            addCriterion("isdeleted not between", value1, value2, "isdeleted");
            return (Criteria) this;
        }

        public Criteria andLianrenIsNull() {
            addCriterion("lianren is null");
            return (Criteria) this;
        }

        public Criteria andLianrenIsNotNull() {
            addCriterion("lianren is not null");
            return (Criteria) this;
        }

        public Criteria andLianrenEqualTo(String value) {
            addCriterion("lianren =", value, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenNotEqualTo(String value) {
            addCriterion("lianren <>", value, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenGreaterThan(String value) {
            addCriterion("lianren >", value, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenGreaterThanOrEqualTo(String value) {
            addCriterion("lianren >=", value, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenLessThan(String value) {
            addCriterion("lianren <", value, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenLessThanOrEqualTo(String value) {
            addCriterion("lianren <=", value, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenLike(String value) {
            addCriterion("lianren like", value, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenNotLike(String value) {
            addCriterion("lianren not like", value, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenIn(List<String> values) {
            addCriterion("lianren in", values, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenNotIn(List<String> values) {
            addCriterion("lianren not in", values, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenBetween(String value1, String value2) {
            addCriterion("lianren between", value1, value2, "lianren");
            return (Criteria) this;
        }

        public Criteria andLianrenNotBetween(String value1, String value2) {
            addCriterion("lianren not between", value1, value2, "lianren");
            return (Criteria) this;
        }

        public Criteria andLiantimeIsNull() {
            addCriterion("liantime is null");
            return (Criteria) this;
        }

        public Criteria andLiantimeIsNotNull() {
            addCriterion("liantime is not null");
            return (Criteria) this;
        }

        public Criteria andLiantimeEqualTo(Date value) {
            addCriterion("liantime =", value, "liantime");
            return (Criteria) this;
        }

        public Criteria andLiantimeNotEqualTo(Date value) {
            addCriterion("liantime <>", value, "liantime");
            return (Criteria) this;
        }

        public Criteria andLiantimeGreaterThan(Date value) {
            addCriterion("liantime >", value, "liantime");
            return (Criteria) this;
        }

        public Criteria andLiantimeGreaterThanOrEqualTo(Date value) {
            addCriterion("liantime >=", value, "liantime");
            return (Criteria) this;
        }

        public Criteria andLiantimeLessThan(Date value) {
            addCriterion("liantime <", value, "liantime");
            return (Criteria) this;
        }

        public Criteria andLiantimeLessThanOrEqualTo(Date value) {
            addCriterion("liantime <=", value, "liantime");
            return (Criteria) this;
        }

        public Criteria andLiantimeIn(List<Date> values) {
            addCriterion("liantime in", values, "liantime");
            return (Criteria) this;
        }

        public Criteria andLiantimeNotIn(List<Date> values) {
            addCriterion("liantime not in", values, "liantime");
            return (Criteria) this;
        }

        public Criteria andLiantimeBetween(Date value1, Date value2) {
            addCriterion("liantime between", value1, value2, "liantime");
            return (Criteria) this;
        }

        public Criteria andLiantimeNotBetween(Date value1, Date value2) {
            addCriterion("liantime not between", value1, value2, "liantime");
            return (Criteria) this;
        }

        public Criteria andPaifarenIsNull() {
            addCriterion("paifaren is null");
            return (Criteria) this;
        }

        public Criteria andPaifarenIsNotNull() {
            addCriterion("paifaren is not null");
            return (Criteria) this;
        }

        public Criteria andPaifarenEqualTo(String value) {
            addCriterion("paifaren =", value, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenNotEqualTo(String value) {
            addCriterion("paifaren <>", value, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenGreaterThan(String value) {
            addCriterion("paifaren >", value, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenGreaterThanOrEqualTo(String value) {
            addCriterion("paifaren >=", value, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenLessThan(String value) {
            addCriterion("paifaren <", value, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenLessThanOrEqualTo(String value) {
            addCriterion("paifaren <=", value, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenLike(String value) {
            addCriterion("paifaren like", value, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenNotLike(String value) {
            addCriterion("paifaren not like", value, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenIn(List<String> values) {
            addCriterion("paifaren in", values, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenNotIn(List<String> values) {
            addCriterion("paifaren not in", values, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenBetween(String value1, String value2) {
            addCriterion("paifaren between", value1, value2, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifarenNotBetween(String value1, String value2) {
            addCriterion("paifaren not between", value1, value2, "paifaren");
            return (Criteria) this;
        }

        public Criteria andPaifatimeIsNull() {
            addCriterion("paifatime is null");
            return (Criteria) this;
        }

        public Criteria andPaifatimeIsNotNull() {
            addCriterion("paifatime is not null");
            return (Criteria) this;
        }

        public Criteria andPaifatimeEqualTo(Date value) {
            addCriterion("paifatime =", value, "paifatime");
            return (Criteria) this;
        }

        public Criteria andPaifatimeNotEqualTo(Date value) {
            addCriterion("paifatime <>", value, "paifatime");
            return (Criteria) this;
        }

        public Criteria andPaifatimeGreaterThan(Date value) {
            addCriterion("paifatime >", value, "paifatime");
            return (Criteria) this;
        }

        public Criteria andPaifatimeGreaterThanOrEqualTo(Date value) {
            addCriterion("paifatime >=", value, "paifatime");
            return (Criteria) this;
        }

        public Criteria andPaifatimeLessThan(Date value) {
            addCriterion("paifatime <", value, "paifatime");
            return (Criteria) this;
        }

        public Criteria andPaifatimeLessThanOrEqualTo(Date value) {
            addCriterion("paifatime <=", value, "paifatime");
            return (Criteria) this;
        }

        public Criteria andPaifatimeIn(List<Date> values) {
            addCriterion("paifatime in", values, "paifatime");
            return (Criteria) this;
        }

        public Criteria andPaifatimeNotIn(List<Date> values) {
            addCriterion("paifatime not in", values, "paifatime");
            return (Criteria) this;
        }

        public Criteria andPaifatimeBetween(Date value1, Date value2) {
            addCriterion("paifatime between", value1, value2, "paifatime");
            return (Criteria) this;
        }

        public Criteria andPaifatimeNotBetween(Date value1, Date value2) {
            addCriterion("paifatime not between", value1, value2, "paifatime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNull() {
            addCriterion("endtime is null");
            return (Criteria) this;
        }

        public Criteria andEndtimeIsNotNull() {
            addCriterion("endtime is not null");
            return (Criteria) this;
        }

        public Criteria andEndtimeEqualTo(Date value) {
            addCriterion("endtime =", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotEqualTo(Date value) {
            addCriterion("endtime <>", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThan(Date value) {
            addCriterion("endtime >", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("endtime >=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThan(Date value) {
            addCriterion("endtime <", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("endtime <=", value, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeIn(List<Date> values) {
            addCriterion("endtime in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotIn(List<Date> values) {
            addCriterion("endtime not in", values, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeBetween(Date value1, Date value2) {
            addCriterion("endtime between", value1, value2, "endtime");
            return (Criteria) this;
        }

        public Criteria andEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("endtime not between", value1, value2, "endtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cgshangbao
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 18 10:32:41 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cgshangbao
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}