package com.jtzh.entity;

import java.util.Date;

public class Hwchuli {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgchuli.id
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgchuli.shangbaoid
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    private Integer shangbaoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgchuli.chuliren
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    private String chuliren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgchuli.chulitime
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    private Date chulitime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgchuli.chulimiaoshu
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    private String chulimiaoshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgchuli.sheheren
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    private String sheheren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgchuli.shehetime
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    private Date shehetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgchuli.shehemiaoshu
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    private String shehemiaoshu;
    private String shenheState;
    public String photo1;

    public String getPhoto1() {
        return photo1;
    }

    public void setPhoto1(String photo1) {
        this.photo1 = photo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgchuli.id
     *
     * @return the value of cgchuli.id
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgchuli.id
     *
     * @param id the value for cgchuli.id
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgchuli.shangbaoid
     *
     * @return the value of cgchuli.shangbaoid
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public Integer getShangbaoid() {
        return shangbaoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgchuli.shangbaoid
     *
     * @param shangbaoid the value for cgchuli.shangbaoid
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setShangbaoid(Integer shangbaoid) {
        this.shangbaoid = shangbaoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgchuli.chuliren
     *
     * @return the value of cgchuli.chuliren
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public String getChuliren() {
        return chuliren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgchuli.chuliren
     *
     * @param chuliren the value for cgchuli.chuliren
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setChuliren(String chuliren) {
        this.chuliren = chuliren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgchuli.chulitime
     *
     * @return the value of cgchuli.chulitime
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public Date getChulitime() {
        return chulitime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgchuli.chulitime
     *
     * @param chulitime the value for cgchuli.chulitime
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setChulitime(Date chulitime) {
        this.chulitime = chulitime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgchuli.chulimiaoshu
     *
     * @return the value of cgchuli.chulimiaoshu
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public String getChulimiaoshu() {
        return chulimiaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgchuli.chulimiaoshu
     *
     * @param chulimiaoshu the value for cgchuli.chulimiaoshu
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setChulimiaoshu(String chulimiaoshu) {
        this.chulimiaoshu = chulimiaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgchuli.sheheren
     *
     * @return the value of cgchuli.sheheren
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public String getSheheren() {
        return sheheren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgchuli.sheheren
     *
     * @param sheheren the value for cgchuli.sheheren
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setSheheren(String sheheren) {
        this.sheheren = sheheren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgchuli.shehetime
     *
     * @return the value of cgchuli.shehetime
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public Date getShehetime() {
        return shehetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgchuli.shehetime
     *
     * @param shehetime the value for cgchuli.shehetime
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setShehetime(Date shehetime) {
        this.shehetime = shehetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgchuli.shehemiaoshu
     *
     * @return the value of cgchuli.shehemiaoshu
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public String getShehemiaoshu() {
        return shehemiaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgchuli.shehemiaoshu
     *
     * @param shehemiaoshu the value for cgchuli.shehemiaoshu
     *
     * @mbggenerated Tue Jul 24 10:13:50 CST 2018
     */
    public void setShehemiaoshu(String shehemiaoshu) {
        this.shehemiaoshu = shehemiaoshu;
    }

	public String getShenheState() {
		return shenheState;
	}

	public void setShenheState(String shenheState) {
		this.shenheState = shenheState;
	}

}