package com.jtzh.entity;

import java.util.Date;

public class Hwshangbao {
	 /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.id
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.Categories
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String categories;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.smallcategories
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String smallcategories;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.submittime
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private Date submittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.dizhi1
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String dizhi1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.dizhi2
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String dizhi2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.people
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String people;
    public String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.photo
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.miaoshu
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String miaoshu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.isdeleted
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.lianren
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String lianren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.liantime
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private Date liantime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.paifaren
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private String paifaren;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.paifatime
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private Date paifatime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cgshangbao.endtime
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    private Date endtime;
    private String quality;
    public String x;
    public String y;
    private String yhzh;
    private String createId;
    private Date createTime;
    private String delflag;
    private String paifabumen;
    private Integer sourceId;
    private String source;
    private Integer countrysideId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.id
     *
     * @return the value of cgshangbao.id
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.id
     *
     * @param id the value for cgshangbao.id
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.Categories
     *
     * @return the value of cgshangbao.Categories
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getCategories() {
        return categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.Categories
     *
     * @param categories the value for cgshangbao.Categories
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setCategories(String categories) {
        this.categories = categories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.smallcategories
     *
     * @return the value of cgshangbao.smallcategories
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getSmallcategories() {
        return smallcategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.smallcategories
     *
     * @param smallcategories the value for cgshangbao.smallcategories
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setSmallcategories(String smallcategories) {
        this.smallcategories = smallcategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.submittime
     *
     * @return the value of cgshangbao.submittime
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.dizhi1
     *
     * @return the value of cgshangbao.dizhi1
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getDizhi1() {
        return dizhi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.dizhi1
     *
     * @param dizhi1 the value for cgshangbao.dizhi1
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setDizhi1(String dizhi1) {
        this.dizhi1 = dizhi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.dizhi2
     *
     * @return the value of cgshangbao.dizhi2
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getDizhi2() {
        return dizhi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.dizhi2
     *
     * @param dizhi2 the value for cgshangbao.dizhi2
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setDizhi2(String dizhi2) {
        this.dizhi2 = dizhi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.people
     *
     * @return the value of cgshangbao.people
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.people
     *
     * @param people the value for cgshangbao.people
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setPeople(String people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.photo
     *
     * @return the value of cgshangbao.photo
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.photo
     *
     * @param photo the value for cgshangbao.photo
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.miaoshu
     *
     * @return the value of cgshangbao.miaoshu
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getMiaoshu() {
        return miaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.miaoshu
     *
     * @param miaoshu the value for cgshangbao.miaoshu
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setMiaoshu(String miaoshu) {
        this.miaoshu = miaoshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.isdeleted
     *
     * @return the value of cgshangbao.isdeleted
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.isdeleted
     *
     * @param isdeleted the value for cgshangbao.isdeleted
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setIsdeleted(String isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.lianren
     *
     * @return the value of cgshangbao.lianren
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getLianren() {
        return lianren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.lianren
     *
     * @param lianren the value for cgshangbao.lianren
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setLianren(String lianren) {
        this.lianren = lianren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.liantime
     *
     * @return the value of cgshangbao.liantime
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.paifaren
     *
     * @return the value of cgshangbao.paifaren
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public String getPaifaren() {
        return paifaren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cgshangbao.paifaren
     *
     * @param paifaren the value for cgshangbao.paifaren
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */
    public void setPaifaren(String paifaren) {
        this.paifaren = paifaren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cgshangbao.paifatime
     *
     * @return the value of cgshangbao.paifatime
     *
     * @mbggenerated Wed Jul 18 10:32:41 CST 2018
     */

    public Date getSubmittime() {
        return submittime;
    }

    public void setSubmittime(Date submittime) {
        this.submittime = submittime;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

	public Date getLiantime() {
		return liantime;
	}

	public void setLiantime(Date liantime) {
		this.liantime = liantime;
	}

	public Date getPaifatime() {
		return paifatime;
	}

	public void setPaifatime(Date paifatime) {
		this.paifatime = paifatime;
	}

	public Date getEndtime() {
		return endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getX() {
		return x;
	}

	public void setX(String x) {
		this.x = x;
	}

	public String getY() {
		return y;
	}

	public void setY(String y) {
		this.y = y;
	}

	public String getCreateId() {
		return createId;
	}

	public void setCreateId(String createId) {
		this.createId = createId;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getYhzh() {
		return yhzh;
	}

	public void setYhzh(String yhzh) {
		this.yhzh = yhzh;
	}

	public String getDelflag() {
		return delflag;
	}

	public void setDelflag(String delflag) {
		this.delflag = delflag;
	}

	public String getQuality() {
		return quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	public String getPaifabumen() {
		return paifabumen;
	}

	public void setPaifabumen(String paifabumen) {
		this.paifabumen = paifabumen;
	}

	public Integer getSourceId() {
		return sourceId;
	}

	public void setSourceId(Integer sourceId) {
		this.sourceId = sourceId;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public Integer getCountrysideId() {
		return countrysideId;
	}

	public void setCountrysideId(Integer countrysideId) {
		this.countrysideId = countrysideId;
	}

}
